version: '3'
services:
  database:
    build: test/integration/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: be-interview-env
    ports:
      - "5432:5432"
    restart: always
  source:
    build: test/integration/source
    ports:
      - "8080:8080"
  app:
    build: .
    depends_on:
      - database
      - source
    environment:
      - TOKEN_HOST=http://source:8080
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=be-interview-env
      - DB_SSLMODE=disable
    command: "10000"
